from __future__ import annotations

"""Resolve a plain ticker (e.g. "RELIANCE") to an Upstox instrument_key.

Upstox addresses instruments by keys like ``NSE_EQ|INE002A01018`` (exchange +
ISIN), not by trading symbol. This module downloads Upstox's published
instruments file once per day, builds a ``{TRADINGSYMBOL -> instrument_key}``
map for NSE/BSE equities, and caches it on disk so the lookup is free after the
first fetch.

The file is gzip-compressed JSON, regenerated by Upstox each morning:
  https://assets.upstox.com/market-quote/instruments/exchange/complete.json.gz

Lookups are case-insensitive on the bare ticker. ``RELIANCE`` resolves to its
NSE equity key by default; pass ``"BSE:TCS"`` to force the BSE segment.

Everything degrades to ``None`` on failure — the caller then has no quote for
that symbol rather than crashing.
"""

import gzip
import json
import logging
import time
from pathlib import Path
from typing import Optional

import httpx

logger = logging.getLogger(__name__)

_INSTRUMENTS_URL = "https://assets.upstox.com/market-quote/instruments/exchange/complete.json.gz"
_CACHE_PATH = Path("data") / "upstox_instruments.json"
_CACHE_TTL_SECONDS = 20 * 60 * 60  # ~1 day; Upstox regenerates each morning

# In-process map: "NSE:RELIANCE" -> "NSE_EQ|INE002A01018". Built lazily.
_MAP: dict[str, str] = {}
_MAP_LOADED_AT: float = 0.0


def _segment_for(exchange: str) -> str:
    """Map a plain exchange to Upstox's equity segment token."""
    return {"NSE": "NSE_EQ", "BSE": "BSE_EQ"}.get(exchange.upper(), "NSE_EQ")


def _download_instruments() -> list[dict]:
    """Fetch + decompress Upstox's complete instruments dump. [] on failure."""
    try:
        with httpx.Client(timeout=60) as client:
            resp = client.get(_INSTRUMENTS_URL)
            resp.raise_for_status()
            raw = gzip.decompress(resp.content)
            return json.loads(raw)
    except Exception as exc:
        logger.warning("[upstox] instruments download failed: %s", exc)
        return []


def _build_map(records: list[dict]) -> dict[str, str]:
    """Build {EXCH:TRADINGSYMBOL -> instrument_key} for NSE/BSE equities."""
    out: dict[str, str] = {}
    for r in records:
        # Upstox records vary; guard every field.
        seg = (r.get("segment") or "").upper()           # e.g. "NSE_EQ"
        tsym = (r.get("trading_symbol") or r.get("tradingsymbol") or "").upper()
        key = r.get("instrument_key") or ""
        itype = (r.get("instrument_type") or "").upper()
        if not (seg and tsym and key):
            continue
        # Equities only — skip F&O, indices, etc.
        if seg not in ("NSE_EQ", "BSE_EQ") or itype not in ("EQ", "EQUITY", ""):
            continue
        exch = "NSE" if seg == "NSE_EQ" else "BSE"
        out[f"{exch}:{tsym}"] = key
    return out


def _ensure_map() -> None:
    """Load the map from disk cache, or download + cache if stale/missing."""
    global _MAP, _MAP_LOADED_AT
    now = time.time()
    if _MAP and (now - _MAP_LOADED_AT) < _CACHE_TTL_SECONDS:
        return

    # Try disk cache first.
    try:
        if _CACHE_PATH.exists() and (now - _CACHE_PATH.stat().st_mtime) < _CACHE_TTL_SECONDS:
            _MAP = json.loads(_CACHE_PATH.read_text(encoding="utf-8"))
            _MAP_LOADED_AT = now
            logger.info("[upstox] instrument map loaded from cache (%d symbols)", len(_MAP))
            return
    except Exception as exc:
        logger.debug("[upstox] cache read failed: %s", exc)

    records = _download_instruments()
    if not records:
        # Keep whatever stale map we have rather than wiping it.
        return
    new_map = _build_map(records)
    if not new_map:
        return
    _MAP = new_map
    _MAP_LOADED_AT = now
    try:
        _CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
        _CACHE_PATH.write_text(json.dumps(_MAP), encoding="utf-8")
    except Exception as exc:
        logger.debug("[upstox] cache write failed: %s", exc)
    logger.info("[upstox] instrument map built + cached (%d symbols)", len(_MAP))


def resolve(symbol: str) -> Optional[str]:
    """Return the Upstox instrument_key for a ticker, or None if unknown.

    Accepts ``"RELIANCE"`` (defaults to NSE) or ``"BSE:TCS"``.
    """
    sym = (symbol or "").upper().strip()
    if not sym:
        return None
    if ":" in sym:
        exch, tsym = sym.split(":", 1)
    else:
        exch, tsym = "NSE", sym
    _ensure_map()
    key = _MAP.get(f"{exch}:{tsym}")
    if key:
        return key
    # NSE miss → try BSE as a courtesy before giving up.
    if exch == "NSE":
        return _MAP.get(f"BSE:{tsym}")
    return None


def resolve_many(symbols: list[str]) -> dict[str, str]:
    """Map each input ticker to its instrument_key. Skips unresolved tickers."""
    out: dict[str, str] = {}
    for s in symbols:
        key = resolve(s)
        if key:
            out[s.upper().strip()] = key
    return out
